### ISSUE TITLE
Installation failed on Mac with errors during npm install

### ISSUE THREAD

**Issue by markusvoelter** [nypublicradio/audiogram#25]
$ npm install                                                          
/
> waveform@3.0.1 install /Users/markusvoelter/Documents/audiogram/audiogram/node_modules/waveform
> node-gyp rebuild

  CC(target) Release/obj.target/waveform/waveform.o
../waveform.c:4:10: fatal error: 'groove/groove.h' file not found
#include <groove/groove.h>
         ^
1 error generated.
make: *** [Release/obj.target/waveform/waveform.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/markusvoelter/Documents/audiogram/audiogram/node_modules/waveform
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> canvas@1.4.0 install /Users/markusvoelter/Documents/audiogram/audiogram/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:23:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/markusvoelter/Documents/audiogram/audiogram/node_modules/canvas
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! waveform@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the waveform@3.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the waveform package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs waveform
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls waveform
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/markusvoelter/Documents/audiogram/audiogram/npm-debug.log

[npm-debug-log.txt](https://github.com/nypublicradio/audiogram/files/397076/npm-debug-log.txt)

**Comment by veltman** [comment]
You appear to be missing at least two dependencies (`jpeg` and `libgroove`).

See: 

https://github.com/nypublicradio/audiogram/blob/master/INSTALL.md#mac-troubleshooting
https://github.com/Automattic/node-canvas#installation
https://github.com/andrewrk/libgroove

**Comment by markusvoelter** [comment]
I did run 
    brew install pkg-config cairo pango libpng jpeg giflib libgroove ffmpeg
though. This should have installed everything, right?

**Comment by veltman** [comment]
It should, but it depends on your operating system, Homebrew version, XCode version, etc. Try following the more detailed instructions in the troubleshooting.

**Comment by markusvoelter** [comment]
Thanks. I'll wait until somebody offers a hosted version.
