### ISSUE TITLE
Docker install?

### ISSUE THREAD

**Issue by kookster** [nypublicradio/audiogram#27]
seems like one way to make this easier to use is having a docker container setup instead, I'll see if I can get that working.

**Comment by veltman** [comment]
See also: #19

@abuiles offered this Dockerfile: https://gist.github.com/abuiles/6645f15f3578987822a8512379069b4e

In general, I think once I finish a few of the pressing features, we'll bundle the renderer as a Lambda task and the editor will be either Docker or an Electron app for easier local installation.

**Comment by veltman** [comment]
Closed with 4d57849
