### ISSUE TITLE
Ubuntu 15.04 or later systemd script

### ISSUE THREAD

**Issue by DefV** [nypublicradio/audiogram#42]
Because I set up audiogram on a Ubuntu 16.04 system I couldn't use the upstart blogpost since they changed to systemd. I figured out how to create a systemd service and create the config for it. To save other people some work I will attach it here, up to you wether you put it in the INSTALL, or as an example file somewhere.

```systemd
# Install this in /lib/systemd/system/audiogram.service
[Unit]
Description=Startup script for audiogram
After=network.target

[Service]
User=<<User to run as>>
WorkingDirectory=<<Where you installed audiogram>>
ExecStart=/usr/bin/npm start -- 8888

[Install]
WantedBy=multi-user.target
```

After putting the file you can enable it by running
```
systemctl reload-daemon
systemctl enable audiogram
systemctl start audiogram
```

**Comment by veltman** [comment]
Thanks, will add some links re: systemd to the docs.
