### ISSUE TITLE
Error: stdout maxBuffer exceeded on long Video (30 minutes)

### ISSUE THREAD

**Issue by DSigmund** [nypublicradio/audiogram#46]
As it says :-)

I recommend to increase the maxbuffer of the exec-calls: 
http://stackoverflow.com/a/23429654

**Comment by veltman** [comment]
Eventually this shouldn't really be an issue because the libgroove dependency will disappear (#37) - you can try it that way using the `alpha` branch. But yes, it's not really designed to handle extremely long videos.

**Comment by mherchel** [comment]
Where do I increase the maxBuffer? Thanks :)
