### ISSUE TITLE
[resolved] login to the port...listening...

### ISSUE THREAD

**Issue by claudinski** [nypublicradio/audiogram#47]
Hi!
I'm just trying to produce my first audiogram. 

I follow all  your **well done** instruction to use on my own. I installed it on Xubuntu 14.04 but when I try to connect to the port through the npm start
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose config Skipping project config: /home/cla/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/cla/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/cla
7 error Linux 4.4.0-36-generic
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
9 error node v6.6.0
10 error npm  v3.10.3
11 error path /home/cla/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/cla/package.json'
16 error enoent ENOENT: no such file or directory, open '/home/cla/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]
`

 the system stay....listening to the 8888 port without any result. Could you please give me some help?

**Comment by veltman** [comment]
I think you're in the wrong directory. Try running this first:

```
cd /home/cla/audiogram/
```

and then running:

```
npm start
```

If that doesn't work, what's the output of running:

```
find . -name audiogram
```

**Comment by claudinski** [comment]
Thanks Noah!

This the output of the first two:

cla@cla-D630:~/audiogram$ npm start

 > audiogram@0.9.4 start /home/cla/audiogram
 > npm run postinstall && bin/server


 > audiogram@0.9.4 postinstall /home/cla/audiogram
 > mkdir -p editor/js && browserify client/index.js > editor/js/bundle.js

info: Listening on 8888

but after three minutes still listening...so I assumed it was not working.

The output of the third is:

cla@cla-D630:~$ find . -name audiogram
./audiogram
./audiogram/audiogram



Il 18/09/2016 17:25, Noah Veltman ha scritto:

**Comment by veltman** [comment]
After it says "Listening" and you open http://localhost:8888/ in a web browser, what happens?

**Comment by claudinski** [comment]
It opens Audiogram!

I missed the step from listening to open localhost!

Great !
