### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by katieshelly** [nypublicradio/audiogram#48]
I'm not sure if this is the right place to ask for help with installing and launching .. please correct me if I'm asking in the wrong place.

This is the message I see in Terminal when I try to launch Audiogram:

npm ERR! Failed at the audiogram@0.9.4 postinstall script 'mkdir -p editor/js && browserify client/index.js > editor/js/bundle.js'.
npm ERR! This is most likely a problem with the audiogram package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdir -p editor/js && browserify client/index.js > editor/js/bundle.js

I just really want to get started using Audiogram! Any help you can provide would be much appreciated. Thank you :)

**Comment by veltman** [comment]
Did you run `npm install`?  Try running it just in case.

If that doesn't work - what do you see if you run the following command from the audiogram directory?

```
./node_modules/.bin/browserify client/index.js
```

**Comment by katieshelly** [comment]
thank you noah! here is what I see

Katies-MacBook-Pro:audiogram katieshelly$ ./node_modules/.bin/browserify client/index.js
-bash: ./node_modules/.bin/browserify: No such file or directory
