### ISSUE TITLE
Modifying themes using Docker?

### ISSUE THREAD

**Issue by vanityclear** [nypublicradio/audiogram#50]
First off, thanks so much for making this available! I'm using Audiogram via the Docker install, and it's working great. My question is about modifying themes. I modified the themes.json file in the GitHub folder on my desktop, but it looks like in order for those changes to happen I need to commit them and make a pull request—but I don't want those changes to show up on the nypublicradio/audiogram repo! Is that what would happen? Is this the right way to modify themes using Docker, or is there something I'm missing?

**Comment by vanityclear** [comment]
I have figured it out! The solutions on the previous threads didn't quite work for me, but I finally came up with the right code, to create a volume mount from my local computer onto the Docker container:

$ docker run -p 8888:8888 -v /Users/<path>/audiogram/settings/:/home/audiogram/audiogram/settings/ -t -i audiogram

**Comment by frenchpress** [comment]
Thank you, vanityclear. Could you help me know when to use that code? In place of docker run -p 8888:8888 -t -i audiogram?

All of this is pretty over my head and I appreciate your help.

**Comment by ooobo** [comment]
Looks like you have an issue with your themes.json
``Error parsing settings/themes.json.

Paste the contents in a json validator.

You could also try the Social Audio slack channel to get a quicker response
btw

**Comment by frenchpress** [comment]
Thank you ooobo! This got me on the right track and we got it fixed. <3
