### ISSUE TITLE
l0st n00b

### ISSUE THREAD

**Issue by frenchpress** [nypublicradio/audiogram#54]
I've never attempted anything like this before. Help?

Installed Docker and Git. Tried both cloning and building.

In OSX Terminal:
docker run -p 8888:8888 -t -i audiogram
gets me to
audiogram@6e5c1a77f2d7:~/audiogram$

What now?

Thanks!

**Comment by veltman** [comment]
You should run `npm start`.

**Comment by frenchpress** [comment]
> audiogram@0.9.4 start /home/audiogram/audiogram
> npm run postinstall && bin/server


> audiogram@0.9.4 postinstall /home/audiogram/audiogram
> mkdir -p editor/js && browserify client/index.js > editor/js/bundle.js

info: Listening on 8888

**Comment by veltman** [comment]
Now open a web browser and visit `http://localhost:8888/`.

**Comment by frenchpress** [comment]
YES!
Thank you, Noah. I can feel the eye rolls. I got so close!
Appreciate you and your work.

**Comment by frenchpress** [comment]
I've taken a couple of hours to try to figure this out, and am coming up short and have been reading threads that seem to be related but are over my head.

I've made some simple changes to themes.json. Different name, color and background image. Image is in the correct folder. Committed in GitHub and synced. This new theme is not showing up in the dropdown menu.

Thank you, again, for your help. I think this is the final thing I will need. I'm not going to be going deep in the code.

**Comment by frenchpress** [comment]
Never mind. We got it fixed! Thank you!
