### ISSUE TITLE
Background picture does not change after editing themes.json

### ISSUE THREAD

**Issue by PhilipBanse** [nypublicradio/audiogram#57]
Hi!

I try to create a theme with a background picture. 

I put the correctly named picture in settings/backgrounds
I edit the themes.json (see below)
- new theme with background picture
- old theme with new background picture

but the new theme does not appear in the pull down menue and the old theme still has the new york subway picture - which isn´t even in settings/backgrounds anymore.

![bildschirmfoto 2016-10-18 um 21 48 59](https://cloud.githubusercontent.com/assets/3398542/19493869/c4a7d9c4-957c-11e6-965e-ae0db7868373.png)

[themes.txt](https://github.com/nypublicradio/audiogram/files/537213/themes.txt)

**Comment by veltman** [comment]
Are you using Docker?  If so, see this issue:

https://github.com/nypublicradio/audiogram/issues/44#issuecomment-246435962

**Comment by veltman** [comment]
Closing as idle, feel free to add additional info if this isn't resolved.
