### ISSUE TITLE
error when hitting generate?

### ISSUE THREAD

**Issue by grm3** [nypublicradio/audiogram#58]
I had a bit of trouble setting this up, but now it appears to be working until I hit the generate button.

Error message.
![capture](https://cloud.githubusercontent.com/assets/23106060/19780460/215884f2-9c53-11e6-8f27-223e11d8e972.JPG)

Then this error message shows up on the webpage itself.
![capture2](https://cloud.githubusercontent.com/assets/23106060/19780501/3e3b19e0-9c53-11e6-8ff8-55ec7ee1f436.JPG)

It seems like the ajax call in bundle.js is going to something that doesn't exist on line 204. I have downloaded various versions of audiogram and can't find any that have a 'submit' directory.

```javascript
$.ajax({
		url: "/submit/",
		type: "POST",
```

Any ideas? I work for the Atlanta Journal and would like to use this for multiple reporters. I am using a remote server running Ubuntu 14.04 and can provide the URL is someone is willing to help.

THANKS,
George Mathis

**Comment by veltman** [comment]
There is no `submit` directory, it's a virtual path defined in the server files. What that error message suggests to me is that the problem is some combination of:

-You're running nginx as a proxy in front of Audiogram, and that's misconfigured
-Audiogram is running on port 80 and you also have another webserver running on the same port, so that's getting tangled up

Possible remedies:
-Running Audiogram on its default port (8888) and visiting it that way (e.g. http://yourdomain:8888/)
-Running it on a separate remote server that's not shared with other web stuff

Let me know if you can't resolve it and I'll try to dig into it some more.

**Comment by grm3** [comment]
Thanks for the quick reply. I have tried various things, such as retooling the nginx setup as per Node.js documentation and I am still getting the same error. (I followed [this guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04) for node and nginx cohabitation.)

I have PM2 running the server and worker and the page is being served up fine, but it seems the paths provided in editor/index (to bundle.js and css) and the paths provided by bundle.js (to theme.json and the background images ... and I assume the SUBMIT function) are returning relative paths, not absolute ones.

I am surely doing something wrong, but I followed the Ubuntu 14+ directions. 

Not sure if you work with nginx much but my conf file looks like this ...

```
server {
listen 80;
#server_name ec2-54-224-152-237.compute-1.amazonaws.com;
server_name 52.4.178.78;


location = /george/audiogram/ {
        proxy_pass http://127.0.0.1:8888/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
...
```

It seems to be serving the html up fine, though I have replaced the relative paths in editor/index.html with absolute paths (otherwise nothing works)

**Thanks for any assistance.** Please excuse my node.js ignorance ... I am not familiar with it, obviously.

I can always look into getting a pure node js instance, but it seems like this should work with an nginx proxy.

**Comment by veltman** [comment]
Unfortunately I can't really help with the nginx side of things, but that does seem to be squarely where the issue is - specifically regarding the relative vs. absolute paths.
