### ISSUE TITLE
Install problems pkg-config-0.28 on Mac (Mavericks)

### ISSUE THREAD

**Issue by JonHille** [nypublicradio/audiogram#59]
Hi, I keep getting configuration errors / permission issues installing the pkg-config-0.28. file
Something about GLIB_CFLAGS and GLIB_LIBS seem to be wrong and 'have to be set to the correct values or pass'.
That's above my head to begin with, but after some searching I tried the following code in terminal:

pkg-config-0.28 Jon$ ./configure --with-internal-glib && make install

But still the permissions don't come thrue.
I'm a newby at the Github and with programming with terminal so any help in the right direction is more than welcome!
Here's my latest log:
[terminal log_17-10.pdf](https://github.com/nypublicradio/audiogram/files/560693/terminal.log_17-10.pdf)

**Comment by veltman** [comment]
I see a few permissions errors, you may want to make sure you `sudo` the `configure` and `make` commands.

Are you unable to install Homebrew? It might greatly simplify the installation of `pkg-config` (and the rest).
