### ISSUE TITLE
Bundle this as an Electron app?

### ISSUE THREAD

**Issue by veltman** [nypublicradio/audiogram#6]
Rather than the current very manual installation process, we could potentially bundle a lot of this into a nice Electron desktop app. Some obstacles:

* [Can't use the bundled FFmpeg](https://github.com/electron/electron/issues/2588)
* Auto-updating would be tricky
* Would have to build a GUI for editing server settings

**Comment by jesusgalvan** [comment]
Is there any additional thoughts on this?

**Comment by veltman** [comment]
I think if I ever get to this it will probably only come after #17 or some other way or offloading all the rendering logic since that would reduce the surface area of stuff that has to get bundled into Electron quite a bit. But if you're interested in working on it, let me know how I can help!
