### ISSUE TITLE
worker errors out, getting "Waiting for other jobs to finish" message

### ISSUE THREAD

**Issue by grm3** [nypublicradio/audiogram#60]
I have created a new virtual server that uses just node (no nginx) and have gotten a bit further along, running the app on port 8080 (changed port in settings/index.js).

I am running server and worker through PM2. Server fires up and looks good, but Worker errors out after a few seconds.

When I hit GENERATE I get a message telling me I am in a queue and to wait. 

But with the Worker dead, I guess it will never render a file. 

Here is a screenshot. Any help is appreciated! Thanks!
![capture](https://cloud.githubusercontent.com/assets/23106060/19938953/478f7348-a0fd-11e6-9218-bfa5eeee56bf.JPG)

**Comment by grm3** [comment]
More info ... it seems I have to add canvas back after removing it per the instructions ... I am running this on a VM with .5 gigs of memory.

How do I reverse this step and add canvas back to dependencies? ... "Remove canvas from the dependencies in package.json"

I could not get this step to work so went with the other option (clang) and could run npm install. ...npm install git+https://github.com/chearon/node-canvas.git#b62dd3a9fa

Thanks for any help.

![capture](https://cloud.githubusercontent.com/assets/23106060/19941094/32f4eba4-a105-11e6-80ee-04783754c5e3.JPG)

**Comment by grm3** [comment]
I tried again from the beginning and it seems I can't get past npm install with only 0.6 gb of memory. 

Here is my debug log if anyone is willing to look at it.

**Comment by veltman** [comment]
Hmm, this might be an npm problem. Can you try updating npm and running again?

```
npm install -g npm
npm install "git+https://github.com/chearon/node-canvas.git#b62dd3a9fa"
```

**Comment by grm3** [comment]
Thanks for the reply. I tried ... still getting the same error ... I guess 0.6 gb of memory is too small to install?
![capture](https://cloud.githubusercontent.com/assets/23106060/19946898/2059a63a-a11c-11e6-9304-e30fb7d77c8d.JPG)

**Comment by JonHille** [comment]
I'm stuck at the same level....:-(

[debug-log JH_04-11.pdf](https://github.com/nypublicradio/audiogram/files/570327/debug-log.JH_04-11.pdf)

**Comment by veltman** [comment]
I think I figured this out - the author of one the dependencies seems to have deleted and recreated his repository on October 21, rendering the URL invalid. Will figure out a fix and update.

**Comment by JonHille** [comment]
Thnx for the effort Noah, much appreciated!

Grtz,

Jon

2016-11-04 21:30 GMT+01:00 Noah Veltman <notifications@github.com>:

**Comment by veltman** [comment]
@JonHille @grm3 I've pushed an update to that URL, can you try installing the latest version?

```
git pull
npm install
```

**Comment by JonHille** [comment]
Great! I will try it out tomorrow.

Op vrijdag 4 november 2016 heeft Noah Veltman <notifications@github.com>
het volgende geschreven:

**Comment by JonHille** [comment]
Almost there.....

Studio-iMac:audiogram Jon$ git pull
Already up-to-date.
Studio-iMac:audiogram Jon$ npm install

> canvas@1.6.0 install /Applications/audiogram/node_modules/canvas
> node-gyp rebuild

Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/audiogram/node_modules/canvas
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/audiogram/npm-debug.log
Studio-iMac:audiogram Jon$

**Comment by JonHille** [comment]
[npm-debug_jonhille_05-11.pdf](https://github.com/nypublicradio/audiogram/files/573431/npm-debug_jonhille_05-11.pdf)

**Comment by veltman** [comment]
@JonHille it looks like that's a node-canvas installation issue, I'd open it as an issue there: https://github.com/Automattic/node-canvas/issues
