### ISSUE TITLE
editor not found, after install with Docker

### ISSUE THREAD

**Issue by JonHille** [nypublicradio/audiogram#62]
I'm still having a hard time opening the Audiogram editor and selecting the template I've edited in the vorked repo of Audiogram.
I only replaced a background (the one with the subway.png) using the exact variables, and the name of the vorked template.
I'm running it on my Windows 10 laptop now, because the install on my Mac (running Mavericks...) made me pull my hair out after two days of trying.

So I was advised to use Docker for Windows, which I did and it worked but without seeing the altered template in the editor. I decided to start a new repo and followed the exact steps in the build-in tutorial in Github desktop by creating a new branch, edit the template and open a pull-request, which I did.

But after reopening docker and doing a rerun with cmd 'docker run -p 8888:8888 -t -i audiogram', followed by 'npm run' I got this error:

Jon@AcerLaptop MINGW64 ~ (master)
$ docker run -p 8888:8888 -t -i audiogram
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint hungry_austin (d35db56e9632c9aff99b31944d5788e2ea3376a3568155cc561f15727c971ea4): Bind for 0.0.0.0:8888 failed: port is already allocated.

So it seems the rerun within Docker wasn't the smartest move, because now I have no connection thrue my browser altogether...

**Comment by JonHille** [comment]
I have the editor up and running again. I closed my active container with Kitematic, and rebuilt it again. But I still can't select my edited theme. Does it have something to do with using Docker next to Github desktop? I came across another issue where Noah was refering to copying file's 'edited in docker' to the audiogram repo folder. But I've never edited anything in Docker, only with Git..?!

**Comment by JonHille** [comment]
...checked the themes.json file. Edits made are visible in both the remote and local repo. I think I'm missing a step while as I open my repo on the github I don't see any changes, other than the .gitignore and README.  So it seems it's not published?!

**Comment by veltman** [comment]
This appears to be resolved?
