### ISSUE TITLE
Support custom image upload backgrounds for individual audiograms

### ISSUE THREAD

**Issue by veltman** [nypublicradio/audiogram#7]
Allow people to upload their own image as the background for an individual audiogram. This would be pretty easy to implement, though it would require some means of scaling/translating the uploaded image.

**Comment by korymath** [comment]
Currently it would be a matter of modifying the themes.json right?

**Comment by veltman** [comment]
This is about letting people upload images for individual audiograms, not for an entire theme (e.g. uploading a photo of the person who's being interviewed in a particular clip).

We haven't prioritized this so far because it would require a whole interface for moving/stretching/position each image and quality control is hard - opening up image uploading like that means it's easy for people to put in photos that look bad or they don't have the rights to.

**Comment by veltman** [comment]
Closing in favor of #32.

**Comment by veproza** [comment]
If anyone would be interested, I added this functionality to our app with this commit: https://github.com/rozhlas/audiogram/commit/921ebd6a06f3c69f13cf10dc185c02ae155e6377. If you'd like, I can make it into a pull request, or feel free to cherry-pick it.

It works that it draws either the uploaded image, the theme image or no image, in this order. The biggest change was the need to handle upload of multiple files, hence the renaming of `req.file` to `req.file.audio`.
