### ISSUE TITLE
INSTALL.md: Linux troubleshooting - PPA launchpad repo then breaks nodesource install script

### ISSUE THREAD

**Issue by iankevinmcdonald** [nypublicradio/audiogram#70]
The Linux install guide suggests adding the Launchpad repository to fetch an ffmpeg package for Ubuntu 13.

Unfortunately, there's now an issue with that repository:
https://blog.launchpad.net/ppa/failed-to-fetch-errors-for-ppas

And this means it breaks the nodesource install script (see: [my nodesource issue report](https://github.com/nodesource/distributions/issues/406), which might or might not be apt for nodesource but describes my problem)

The workaround is to remove the repository once ffmpeg is safely installed; it'd be great if you could mention this in the "Linux troubleshooting" section.

**Comment by veltman** [comment]
This error was on Ubuntu 13, correct? The install guide only covers 14.04+, and that blog post is from 2011. It seems possible to me that you saw an error because of your version rather than because of that old bug, since that PPA has only been tested for 14.04 and above.

**Comment by iankevinmcdonald** [comment]
I'm sorry - I meant that it suggests it for Ubuntu 14. My bad.

I was using Ubuntu *12*. I'll accept it's a version thing. I'd been putting too much faith in apt-get, including negotiating version differences gracefully, but there are limits, particularly if you go about adding repositories.

 If you want to include Ubuntu 12 in the installation guide, I'd be delighted to help.
