### ISSUE TITLE
INSTALL.md - requesting documenting specific ffmpeg requirements

### ISSUE THREAD

**Issue by iankevinmcdonald** [nypublicradio/audiogram#71]
I'm installing audiogram on my old 2008 netbook. It was running Linux Mint Maya - which is Ubuntu 12, so I had to compile ffmpeg.

FFmpeg compilation is a disk space hog, and I had to strip down the install to make it work; and then find out by trial and error what it needed. It'd be really useful to state the detailed ffmpeg dependencies somewhere or other.

This was my final compile command:
`PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure   --prefix="$HOME/ffmpeg_build"   --pkg-config-flags="--static"   --extra-cflags="-I$HOME/ffmpeg_build/include"   --extra-ldflags="-L$HOME/ffmpeg_build/lib"   --bindir="$HOME/bin"   --enable-gpl   --enable-libass   --enable-libfreetype   --enable-libmp3lame --enable-libtheora   --enable-nonfree --disable-ffserver --disable-doc --enable-small --enable-libx264 --enable-libfdk-aac`

Based on these requirements:
- libmp3lame
- libx264
- libfdk-aac
- nonfree

As well as the probably-useful for me:
- small (prioritising size over speed)

And being able to disable these to save space
- ffserver
- doc (*obvious*)

It'd be really useful if it was listed somewhere what's required and what can be dropped. Perhaps the requirements list could just have a parenthetical link to a list afterwards, or even to this issue if it's useful?

**Comment by veltman** [comment]
I'm a little wary of getting too deep into specifying requirements for older, unsupported OSes, since custom FFmpeg compilation can become a pretty tangled web and what worked for one person may not work for another because of non-obvious differences in the two environments - I'll try to add a note about custom compilation with a link to a good guide elsewhere.
