### ISSUE TITLE
Audiogram issues

### ISSUE THREAD

**Issue by sofianebenzaza** [nypublicradio/audiogram#72]
Hi,

Sorry for the vague subject but after a few good tries with converting mp3s into waveforms, I had similar issues than in #63 and it was fixed until it starting bugging again. I am on a iMac on OS X El Capitan and after deleting all of my audiogram folders, I re-installed it again and has issues.

This error was coming before reputting the redis line as you showed in the index.js :  ready state = 0 then after putting the redis line, I get errors when putting npm start on the commande line.

 I am just confused at this point. ( not very tech saavy on these kind of things :) )

Here is my latest log file if it helps. I will give as much information needed vis a vis the errors I get.

Merci

Sofiane
[npm-debug.txt](https://github.com/nypublicradio/audiogram/files/680289/npm-debug.txt)

**Comment by veltman** [comment]
Hmm, it's hard to say based on the log.  One possibility is that the port is already in use by something else (maybe even a previous installation of Audiogram).

If your `settings/index.js` is the only thing you changed, and it doesn't contain any sensitive information, can you attach it?

A few things to try (all from the Audiogram root directory):

1. Run `npm start -- 9999` to use a different port and see what happens.
2. Run `npm run postinstall` first, then if that's successful, run `DEBUG=1 node bin/server`. What does the log look like?
3. Run `redis-cli` to test whether Redis is running/accessible.

**Comment by sofianebenzaza** [comment]
Thx for the update. My results are below

1- I was given a JSON input error but I took out the Redis line in my index file so put it back and another error

2- postinstall worked but the debug gave me the following log.  I know nothing about scripts and basic code so I am sure that I am correctly putting in the redis line

Error parsing settings/index.js.
/Users/Kukla/Documents/audiogram/settings/index.js:21
redisHost: "127.0.0.1”
           ^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/Kukla/Documents/audiogram/lib/settings/load.js:9:14)
    at Object.<anonymous> (/Users/Kukla/Documents/audiogram/lib/settings/index.js:6:16)

3- iMac:audiogram Kukla$ redis-cli
-bash: redis-cli: command not found


I also attached my index.js file.

Thx in advance!
[index.js.zip](https://github.com/nypublicradio/audiogram/files/695042/index.js.zip)

**Comment by ooobo** [comment]
Looks like you need to install redis
`sudo apt-get install redis-server --yes
`

**Comment by veltman** [comment]
There are a few possible issues:

1. There is an error in your `index.js` file - the line that begins with `redisHost` has been pasted into a random spot where it causes an error. It needs to be in `module.exports` like so:

```js
module.exports = {
  workingDirectory: path.join(__dirname, "..", "tmp"),
  storagePath: path.join(__dirname, "..", "media"),
  redisHost: "127.0.0.1",
  fonts: [
    { family: "Source Sans Pro", file: path.join(__dirname, "fonts", "SourceSansPro-Regular.ttf") },
    { family: "Source Sans Pro", file: path.join(__dirname, "fonts", "SourceSansPro-Light.ttf"), weight: 300 },
    { family: "Source Sans Pro", file: path.join(__dirname, "fonts", "SourceSansPro-Bold.ttf"), weight: "bold" },
    { family: "Source Sans Pro", file: path.join(__dirname, "fonts", "SourceSansPro-Italic.ttf"), style: "italic" },
    { family: "Source Sans Pro", file: path.join(__dirname, "fonts", "SourceSansPro-BoldItalic.ttf"), weight: "bold", style: "italic" }
  ]
};
```

2. You may or may not have successfully installed Redis.  If you're on a Mac with Homebrew, try running `brew install redis`

**Comment by veltman** [comment]
Closing as idle.
