### ISSUE TITLE
Browsers will not open http://localhost:8888/

### ISSUE THREAD

**Issue by greylockglass** [nypublicradio/audiogram#80]
UPDATE:
I trashed the previous installation and re-installed. When I did I got the error message

> Failed at the canvas@1.6.0 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the canvas package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs canvas
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls canvas
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> /Users/bob/Applications/audiogram/npm-debug.log

I believe I saw this error after the last install, as well.  just downloaded node.js and npm, so that's not the problem.

I following the directions to the letter, as far as I can tell.

Thanks for your time and attention!

I'm sure there's an answer to this somewhere, but I'm not finding it—apologies if I'm just being daft. I get as far as:

> info: Listening on 8888 

but when I try to load http://localhost:8888/ into any browser, I get a blank page in FF, and in Chrome I get

> This site can't be reached
> The webpage at http://localhost:8888/ might be temporarily down or it may have moved permanently to a new address.
> ERR_SOCKET_NOT_CONNECTED

In Safari, I get:

> Safari Can't Open the Page
> Safari can't open the page "http://localhost:8888/" because the server unexpectedly dropped the connection. This sometimes occurs when the server is busy. Wait for a few minutes, and then try again.

I feel like I'm sooooo close, but the grapes are JUST beyond my grasp. Help? Please?

Thanks!

Jason

**Comment by veltman** [comment]
I'm not sure about the latter error, but it looks like `canvas` is failing to install. Did you successfully install the dependencies first (https://github.com/nypublicradio/audiogram/blob/master/INSTALL.md#mac-os-x-installation)? If so, do you have a more complete error log from the installation?  I would open an issue here: https://github.com/Automattic/node-canvas/issues

**Comment by greylockglass** [comment]
THANKS for the reply @veltman ! This is going to sound stupid, but I turned my computer off, and then back on again, and it worked. Like that's ever really useful, right!?

**Comment by veltman** [comment]
Glad it's resolved!
