### ISSUE TITLE
Rollover Call to Action link in Twitter

### ISSUE THREAD

**Issue by jeremylach** [nypublicradio/audiogram#82]
Trying to figure out how to set the call to action link in the top right when rolling over the video on twitter.  Can't seem to find this documented anywhere.  Thanks!

**Comment by machito** [comment]
+1

**Comment by veltman** [comment]
This is a Twitter platform thing, documented in our instructions for producers here (page 7): 

https://docs.google.com/document/d/1US1llZexMtJi0uIYT_GKShFlD2nRjRmZuVB024zOjSo/edit

It looks like they've changed things a bit and consolidated video.twitter.com into studio.twitter.com (Media Studio). But you should still be able to add calls to action from there if you're able to enroll.

Hope that helps!
