### ISSUE TITLE
Configuring for AWS/Elastic Beanstalk

### ISSUE THREAD

**Issue by gsalkin** [nypublicradio/audiogram#83]
Elastic Beanstalk instances are configured using Amazon's Linux AMI, which has almost none of the dependencies that `node-canvas` needs.  I was able to find the instructions for configuring all of them [here](https://github.com/Automattic/node-canvas/wiki/Installation---Amazon-Linux-AMI-(EC2)).  
* Note that this requires root access to the elastic beanstalk by installing the `aws_cli`, using `sudo su` to gain root and then running through all the installations and compilers.

Would definitely be good to work on the docs to add this info seeing as how EB is a kinda popular PaaS for node apps.  (Has anyone had better success with Heroku?)

Next issue after that is properly setting up the ports so Nginx doesn't send back a 502.  Anyone have info on how to change the default ports on this implementation of `express` so that it connects on the default port?

**Comment by veltman** [comment]
Added a note about Amazon Linux to the installation instructions.

Re: the port, you can configure it with an extra argument (`npm start -- my_special_port_number`) or you can manually edit `bin/server`, where the express app starts.
