### ISSUE TITLE
Doing story for Current.org mentioning Audiogram

### ISSUE THREAD

**Issue by hearvox** [nypublicradio/audiogram#86]
Questions: Hey, devs, I'm researching an article for Current.org about embedding audio on social posts. Definitely want to mention Audiogram (have a local copy running well on my computer, BTW).

Who can I talk to at WNYC about this app? Also, is this the most actively maintained version (vs the NPR Apps fork)? 

Lastly, WNYC designed a nice Twitter Card audio player awhile ago, but the station doesn't use it anymore. Reasons?
https://twitter.com/WNYC/status/471683856291356672

Thanks for any and all insights.

**Comment by noslouch** [comment]
Hey Barrett,

You can better reach us digital ops folks at digitalops@nypublicradio.org. Let's continue this conversation over email.
